approve:
- lgtm_acts_as_approve: false
  repos:
  - test1612/lighthouse-config
  - test1612/hello
  require_self_approval: true
config_updater:
  gzip: false
  maps:
    config.yaml:
      name: config
    plugins.yaml:
      name: plugins
triggers:
- repos:
  - test1612/hello
  ignore_ok_to_test: false
  elide_skipped_contexts: false
plugins:
  test1612/lighthouse-config:
  - config-updater
  - approve
  - lgtm  
  test1612/hello:
  - approve
  - lgtm
  - trigger
